"""Simplified Gradio app for the DARQ DaTSCAN quantification pipeline.

Place this file at the root of the repository, next to the `darq/`, `data/`,
and `scripts/` folders. Then run:

    py app_darq_volbrain.py

This version follows the agreed workflow:
- uploads DaTSCAN, MRI/T1w and SynthSeg files;
- runs the existing pipeline with fixed options: --opt_str lbfgs --force --cpu;
- shows the complete TSV tables generated by the backend, without recomputing metrics;
- shows qualitative MRI / registered DaTSCAN / overlay images;
- generates a PDF report inspired by the volBrain / petBrain report layout.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Iterable

import gradio as gr
import nibabel as nib
import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


ROOT_DIR = Path(__file__).resolve().parent
RUNS_DIR = ROOT_DIR / "gradio_runs"
APP_TITLE = "DARQ - DaTSCAN Quantification Report"

# Fixed execution options for the demo app.
# The app is designed for one subject per run, so recomputation and CPU execution
# are always enabled for predictable local behaviour.
DEFAULT_OPTIMIZER = "lbfgs"
FORCE_RECOMPUTE = True
USE_CPU = True

# PDF style inspired by the provided volBrain / petBrain example.
REPORT_BLUE = "#001A8D"
REPORT_LIGHT_BLUE = "#DDE4FF"
REPORT_GREY = "#e8e8e8"
REPORT_DARK_GREY = "#555555"
REPORT_RED = "#b23b3b"


# -----------------------------------------------------------------------------
# File and execution helpers
# -----------------------------------------------------------------------------

def _find_pipeline_script() -> Path:
    """Return the expected pipeline script path."""
    candidates = [
        ROOT_DIR / "scripts" / "dat2mri.py",
        ROOT_DIR / "dat2mri.py",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate

    raise FileNotFoundError(
        "No pipeline script was found. Expected scripts/dat2mri.py or dat2mri.py "
        "in the project root."
    )


def _check_nifti_extension(path: Path) -> None:
    """Check that the uploaded file looks like a NIfTI image."""
    if not (path.name.endswith(".nii") or path.name.endswith(".nii.gz")):
        raise ValueError(
            f"The file {path.name} does not seem to be a valid NIfTI file. "
            "It must end with .nii or .nii.gz."
        )


def _copy_uploaded_file(uploaded_path: str | None, destination_dir: Path, name: str) -> Path:
    """Copy a Gradio-uploaded file to a stable run folder."""
    if uploaded_path is None:
        raise ValueError(f"Missing uploaded file: {name}")

    source = Path(uploaded_path)
    if not source.exists():
        raise FileNotFoundError(f"Uploaded file not found: {source}")

    _check_nifti_extension(source)

    suffix = ".nii.gz" if source.name.endswith(".nii.gz") else source.suffix
    destination = destination_dir / f"{name}{suffix}"
    shutil.copy2(source, destination)
    return destination


def _read_first_tsv(output_dir: Path, pattern: str) -> pd.DataFrame:
    """Read the first TSV matching a pattern, or return an empty table."""
    matches = sorted(output_dir.glob(pattern))
    if not matches:
        return pd.DataFrame()
    return pd.read_csv(matches[0], sep="\t")


def _format_number(value, digits: int = 4) -> str:
    """Format numbers for report tables without changing the underlying values."""
    try:
        if pd.isna(value):
            return "—"
        if isinstance(value, (float, np.floating)):
            return f"{float(value):.{digits}f}"
        if isinstance(value, (int, np.integer)):
            return str(int(value))
    except Exception:
        pass
    return str(value)


def _format_df_for_display(df: pd.DataFrame, digits: int = 4) -> pd.DataFrame:
    """Round numeric columns only for Gradio readability."""
    if df.empty:
        return df
    out = df.copy()
    for col in out.columns:
        if pd.api.types.is_numeric_dtype(out[col]):
            out[col] = out[col].round(digits)
    return out


def _status_text(completed: subprocess.CompletedProcess[str], output_dir: Path,
                 sbr_raw: pd.DataFrame, symm_raw: pd.DataFrame) -> str:
    """Build a compact status string stored in the generated PDF."""
    stdout = completed.stdout or ""
    stderr = completed.stderr or ""
    if completed.returncode == 0:
        status = "Pipeline completed successfully.\n\n"
    else:
        status = "Pipeline finished with errors.\n\n"

    status += f"Output folder:\n{output_dir}\n\n"
    status += f"SBR rows found: {len(sbr_raw)}\n"
    status += f"Symmetry rows found: {len(symm_raw)}\n\n"
    status += "Terminal output:\n"
    status += stdout[-4000:] if stdout else "(no standard output)"

    if stderr:
        status += "\n\nWarnings / errors:\n"
        status += stderr[-4000:]

    return status


# -----------------------------------------------------------------------------
# Image visualization
# -----------------------------------------------------------------------------

def _find_resampled_dat(output_dir: Path) -> Path | None:
    """Find the registered/resampled DaT image generated by the pipeline."""
    candidates = sorted(output_dir.glob("*_desc-resampled_dat.nii.gz"))
    if candidates:
        return candidates[0]
    candidates = sorted(output_dir.glob("*_dat.nii.gz"))
    return candidates[0] if candidates else None


def _load_nifti_array(path: Path) -> np.ndarray:
    """Load a NIfTI image as a finite 3D float array."""
    arr = np.asarray(nib.load(str(path)).get_fdata(), dtype=np.float32)
    arr = np.squeeze(arr)
    if arr.ndim > 3:
        arr = arr[..., 0]
    arr = np.nan_to_num(arr, nan=0.0, posinf=0.0, neginf=0.0)
    return arr


def _robust_normalize(arr: np.ndarray, lower: float = 1, upper: float = 99) -> np.ndarray:
    """Normalize an array to [0, 1] using robust percentiles for visualization."""
    arr = np.asarray(arr, dtype=np.float32)
    finite = arr[np.isfinite(arr)]
    if finite.size == 0:
        return np.zeros_like(arr, dtype=np.float32)

    lo, hi = np.percentile(finite, [lower, upper])
    if hi <= lo:
        hi = float(np.max(finite))
        lo = float(np.min(finite))
    if hi <= lo:
        return np.zeros_like(arr, dtype=np.float32)

    return np.clip((arr - lo) / (hi - lo), 0, 1)


def _slice2d(arr: np.ndarray, axis: int, index: int) -> np.ndarray:
    """Extract and rotate one 2D slice for display."""
    index = int(np.clip(index, 0, arr.shape[axis] - 1))
    sl = np.take(arr, index, axis=axis)
    return np.rot90(sl)


def _resize_like(image: np.ndarray, target_shape: tuple[int, int]) -> np.ndarray:
    """Resize a 2D image for visualization only."""
    if image.shape == target_shape:
        return image
    try:
        from skimage.transform import resize
        return resize(
            image,
            target_shape,
            preserve_range=True,
            anti_aliasing=True,
        ).astype(np.float32)
    except Exception:
        out = np.zeros(target_shape, dtype=np.float32)
        min0 = min(target_shape[0], image.shape[0])
        min1 = min(target_shape[1], image.shape[1])
        out[:min0, :min1] = image[:min0, :min1]
        return out


def _dat_center_indices(dat: np.ndarray) -> np.ndarray:
    """Choose display slices around the high-uptake DaT region."""
    if dat.size == 0 or np.max(dat) <= 0:
        return np.asarray(dat.shape) // 2

    threshold = np.percentile(dat[dat > 0], 95) if np.any(dat > 0) else np.percentile(dat, 95)
    coords = np.argwhere(dat >= threshold)
    if coords.size == 0:
        return np.asarray(dat.shape) // 2

    return np.round(np.median(coords, axis=0)).astype(int)


def _create_overlay_gallery(mri_path: Path, output_dir: Path, run_dir: Path) -> list[tuple[str, str]]:
    """Create axial/coronal/sagittal MRI-DaT overlay images for the Gradio gallery."""
    dat_path = _find_resampled_dat(output_dir)
    if dat_path is None:
        return []

    mri = _load_nifti_array(mri_path)
    dat = _load_nifti_array(dat_path)

    if mri.ndim != 3 or dat.ndim != 3:
        return []

    display_dir = run_dir / "display"
    display_dir.mkdir(exist_ok=True)

    dat_center = _dat_center_indices(dat)
    views = [
        ("Axial", 2),
        ("Coronal", 1),
        ("Sagittal", 0),
    ]

    gallery: list[tuple[str, str]] = []
    for view_name, axis in views:
        dat_idx = int(dat_center[axis])
        mri_idx = int(round(dat_idx / max(dat.shape[axis] - 1, 1) * max(mri.shape[axis] - 1, 1)))

        mri_slice = _robust_normalize(_slice2d(mri, axis, mri_idx))
        dat_slice = _robust_normalize(_slice2d(dat, axis, dat_idx), lower=5, upper=99.5)
        dat_slice = _resize_like(dat_slice, mri_slice.shape)

        fig, axes = plt.subplots(1, 3, figsize=(10, 3.4), facecolor="white")
        for ax in axes:
            ax.axis("off")

        axes[0].imshow(mri_slice, cmap="gray")
        axes[0].set_title("MRI / T1w", fontsize=10)

        axes[1].imshow(dat_slice, cmap="hot")
        axes[1].set_title("Registered DaTSCAN", fontsize=10)

        axes[2].imshow(mri_slice, cmap="gray")
        masked_dat = np.ma.masked_where(dat_slice <= 0.05, dat_slice)
        axes[2].imshow(masked_dat, cmap="hot", alpha=0.55)
        axes[2].set_title("Overlay", fontsize=10)

        fig.tight_layout()
        out_path = display_dir / f"overlay_{view_name.lower()}.png"
        fig.savefig(out_path, dpi=170, bbox_inches="tight")
        plt.close(fig)

        gallery.append((str(out_path), view_name))

    return gallery


def _create_single_slice_image(source_path: Path, run_dir: Path, name: str, cmap: str = "gray") -> Path | None:
    """Create one axial preview image from an input NIfTI file."""
    try:
        arr = _load_nifti_array(source_path)
        if arr.ndim != 3:
            return None
        idx = _dat_center_indices(arr)[2] if name.lower().startswith("dat") else arr.shape[2] // 2
        sl = _robust_normalize(_slice2d(arr, 2, idx), lower=1, upper=99)
        out_dir = run_dir / "display"
        out_dir.mkdir(exist_ok=True)
        out_path = out_dir / f"preview_{name}.png"

        fig, ax = plt.subplots(figsize=(3.2, 3.2), facecolor="black")
        ax.imshow(sl, cmap=cmap)
        ax.axis("off")
        fig.savefig(out_path, dpi=180, bbox_inches="tight", pad_inches=0)
        plt.close(fig)
        return out_path
    except Exception:
        return None


# -----------------------------------------------------------------------------
# PDF report helpers
# -----------------------------------------------------------------------------

def _draw_header(fig: plt.Figure, title: str = "DARQ report") -> None:
    """Draw a volBrain-like blue report header."""
    ax = fig.add_axes([0.04, 0.91, 0.92, 0.065])
    ax.set_facecolor(REPORT_BLUE)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.text(0.025, 0.5, title, color="white", fontsize=24, va="center", ha="left", fontweight="bold")
    ax.text(0.975, 0.78, "For research only", color="white", fontsize=8, va="center", ha="right")
    fig.text(0.5, 0.895, "version 0.1 - generated by DARQ Gradio app", fontsize=7, ha="center", style="italic")


def _draw_section_bar(fig: plt.Figure, y: float, text: str, color: str = REPORT_BLUE,
                      height: float = 0.026, text_color: str = "white") -> None:
    """Draw a colored section bar."""
    ax = fig.add_axes([0.04, y, 0.92, height])
    ax.set_facecolor(color)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.text(0.015, 0.5, text, color=text_color, fontsize=10, fontweight="bold", va="center", ha="left")


def _df_rows_for_pdf(df: pd.DataFrame, max_rows: int | None = None) -> tuple[list[str], list[list[str]]]:
    """Convert a DataFrame to string rows for matplotlib table rendering."""
    if df.empty:
        return ["No data"], [["No data available"]]

    display_df = df.copy()
    if max_rows is not None:
        display_df = display_df.head(max_rows)

    columns = [str(c) for c in display_df.columns]
    rows = []
    for _, row in display_df.iterrows():
        rows.append([_format_number(v) for v in row.values])
    return columns, rows


def _draw_table(
    ax: plt.Axes,
    df: pd.DataFrame,
    title: str,
    max_rows: int | None = None,
    font_size: int = 7,
    scale_y: float = 1.2,
) -> None:
    """Draw a DataFrame on a matplotlib axis."""
    ax.axis("off")
    ax.set_title(title, loc="left", fontsize=11, fontweight="bold", pad=10)

    columns, rows = _df_rows_for_pdf(df, max_rows=max_rows)
    table = ax.table(
        cellText=rows,
        colLabels=columns,
        loc="center",
        cellLoc="center",
        colLoc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(font_size)
    table.scale(1, scale_y)

    for (r, c), cell in table.get_celld().items():
        if r == 0:
            cell.set_facecolor(REPORT_BLUE)
            cell.set_text_props(color="white", weight="bold")
        elif r % 2 == 0:
            cell.set_facecolor("#f1f1f1")
        else:
            cell.set_facecolor("white")


def _mean_rows_from_sbr(raw_sbr: pd.DataFrame) -> pd.DataFrame:
    """Extract aggregate=mean rows directly from the backend SBR TSV."""
    if raw_sbr.empty:
        return pd.DataFrame()

    df = raw_sbr.copy()
    if "aggregate" in df.columns:
        df = df[df["aggregate"] == "mean"].copy()

    hemi_order = {"R": 0, "L": 1, "Both": 2}
    if "hemi" in df.columns:
        df["_order"] = df["hemi"].map(hemi_order).fillna(99)
        df = df.sort_values("_order").drop(columns=["_order"])

    return df


def _dat_biomarker_pdf_table(raw_sbr: pd.DataFrame) -> pd.DataFrame:
    """Build an SBR table from backend mean uptake values.

    SBR = regional mean uptake / occipital mean uptake - 1.
    """
    mean_df = _mean_rows_from_sbr(raw_sbr)
    if mean_df.empty:
        return pd.DataFrame(columns=["Region", "Right SBR", "Left SBR", "Bilateral SBR"])

    def get_val(hemi: str, col: str):
        if "hemi" not in mean_df.columns or col not in mean_df.columns:
            return np.nan
        rows = mean_df[mean_df["hemi"] == hemi]
        return rows.iloc[0][col] if not rows.empty else np.nan

    def sbr(hemi: str, region_col: str):
        region_value = get_val(hemi, region_col)
        occ_value = get_val(hemi, "dat_occ")
        if pd.isna(region_value) or pd.isna(occ_value) or occ_value == 0:
            return np.nan
        return region_value / occ_value - 1

    mapping = {
        "Striatum": "dat_str",
        "Caudate": "dat_cau",
        "Putamen": "dat_put",
    }

    rows = []
    for region, col in mapping.items():
        rows.append({
            "Region": region,
            "Right SBR": sbr("R", col),
            "Left SBR": sbr("L", col),
            "Bilateral SBR": sbr("Both", col),
        })

    return pd.DataFrame(rows)

def _symmetry_pdf_table(raw_symm: pd.DataFrame) -> pd.DataFrame:
    """Build a compact symmetry table using aggregate=mean rows from *_symm.tsv.

    """
    if raw_symm.empty:
        return pd.DataFrame(columns=["Metric", "Region", "Right", "Left", "Bilateral"])

    df = raw_symm.copy()

    if "aggregate" in df.columns:
        df = df[df["aggregate"] == "mean"].copy()

    def get_val(metric: str, hemi: str, col: str):
        needed = {"metric", "hemi", col}
        if not needed.issubset(df.columns):
            return np.nan

        rows = df[(df["metric"] == metric) & (df["hemi"] == hemi)]
        return rows.iloc[0][col] if not rows.empty else np.nan

    rows = []
    for metric in ["lncc", "l2"]:
        for region, col in {
            "Caudate": "dat_cau",
            "Putamen": "dat_put",
        }.items():
            rows.append({
                "Metric": metric,
                "Region": region,
                "Right": get_val(metric, "R", col),
                "Left": get_val(metric, "L", col),
                "Bilateral": get_val(metric, "Both", col),
            })

    return pd.DataFrame(rows)

def _quality_control(completed: subprocess.CompletedProcess[str], raw_sbr: pd.DataFrame) -> str:
    """Return simple execution quality label."""
    if completed.returncode == 0 and not raw_sbr.empty:
        return "A"
    if completed.returncode == 0:
        return "B"
    return "C"


def _add_image_to_fig(fig: plt.Figure, img_path: str | Path | None,
                      rect: list[float], title: str | None = None,
                      title_color: str = "black") -> None:
    """Add an image to a figure in a fixed rectangle."""
    ax = fig.add_axes(rect)
    ax.axis("off")
    if img_path is None or not Path(img_path).exists():
        ax.text(0.5, 0.5, "No image", ha="center", va="center", fontsize=10)
    else:
        image = plt.imread(str(img_path))
        ax.imshow(image)
    if title:
        ax.set_title(title, fontsize=9, color=title_color, pad=4)


def _create_pdf_report(
    run_dir: Path,
    subject_id: str,
    dat_input_path: Path,
    mri_input_path: Path,
    raw_sbr: pd.DataFrame,
    raw_symm: pd.DataFrame,
    overlay_gallery: list[tuple[str, str]],
    completed: subprocess.CompletedProcess[str],
    status_text: str,
    ) -> Path | None:
    """Create a volBrain-inspired PDF report for DARQ outputs."""
    pdf_path = run_dir / "DARQ_report.pdf"

    try:
        with PdfPages(pdf_path) as pdf:
            qc = _quality_control(completed, raw_sbr)
            biomarker_table = _dat_biomarker_pdf_table(raw_sbr)
            symmetry_table = _symmetry_pdf_table(raw_symm)
            dat_preview = _create_single_slice_image(dat_input_path, run_dir, "dat_input", cmap="gray")
            mri_preview = _create_single_slice_image(mri_input_path, run_dir, "mri_input", cmap="gray")

            # -----------------------------------------------------------------
            # Page 1: volBrain-like summary page
            # -----------------------------------------------------------------
            fig = plt.figure(figsize=(8.27, 11.69), facecolor="white")
            _draw_header(fig, "DARQ report")

            _draw_section_bar(fig, 0.865, f"Subject: {subject_id or 'N/A'}")

            # Metadata table on the left.
            meta_ax = fig.add_axes([0.04, 0.715, 0.23, 0.11])
            meta_ax.axis("off")
            meta_rows = [
                ["DaTSCAN", dat_input_path.name],
                ["MRI / T1w", mri_input_path.name],
                ["Report date", datetime.now().strftime("%d-%b-%Y")],
            ]
            meta_table = meta_ax.table(
                cellText=meta_rows,
                colLabels=None,
                cellLoc="left",
                loc="center",
            )
            meta_table.auto_set_font_size(False)
            meta_table.set_fontsize(8)
            meta_table.scale(1, 1.5)
            for (r, c), cell in meta_table.get_celld().items():
                cell.set_edgecolor("white")
                cell.set_facecolor(REPORT_GREY if r % 2 == 0 else "white")
                if c == 0:
                    cell.set_text_props(weight="bold")

            # Input image previews.
            top_y = 0.665
            _add_image_to_fig(fig, dat_preview, [0.30, top_y, 0.29, 0.16], "DaTSCAN")
            _add_image_to_fig(fig, mri_preview, [0.66, top_y, 0.23, 0.16], "T1w")

            _draw_section_bar(fig, 0.625, "DaTSCAN / MRI qualitative images")

            # Main overlay views.
            if overlay_gallery:
                y_positions = [0.42, 0.215, 0.01]
                for (img_path, caption), y in zip(overlay_gallery[:3], y_positions):
                    _add_image_to_fig(fig, img_path, [0.06, y, 0.88, 0.17], f"{caption} view")
            else:
                fig.text(0.06, 0.50, "No overlay images were generated.", fontsize=11)

            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)

            # -----------------------------------------------------------------
            # Page 2: biomarkers + symmetry + classification + atrophy summary
            # -----------------------------------------------------------------
            fig = plt.figure(figsize=(8.27, 11.69), facecolor="white")
            _draw_header(fig, "DARQ report")

            _draw_section_bar(fig, 0.855, "DaTSCAN quantitative biomarkers (SBR)")

            ax = fig.add_axes([0.06, 0.665, 0.88, 0.15])
            _draw_table(
                ax,
                biomarker_table,
                "SBR by region",
                font_size=8,
                scale_y=1.45,
            )

            _draw_section_bar(fig, 0.585, "DaTSCAN symmetry biomarkers (mean)")

            symm_ax = fig.add_axes([0.06, 0.405, 0.88, 0.14])
            _draw_table(
                symm_ax,
                symmetry_table,
                "Mean symmetry values by region",
                font_size=8,
                scale_y=1.35,
            )

            _draw_section_bar(fig, 0.335, "Classification")
            class_ax = fig.add_axes([0.06, 0.265, 0.88, 0.055])
            class_ax.axis("off")
            class_ax.text(
                0.0,
                0.65,
                "Healthy control / Parkinson's disease classification:",
                fontsize=10,
                fontweight="bold",
            )
            class_ax.text(
                0.0,
                0.20,
                "Not implemented in the current backend version.",
                fontsize=10,
                color=REPORT_RED,
            )

            _draw_section_bar(fig, 0.215, "MRI atrophy quantification")
            atrophy_ax = fig.add_axes([0.06, 0.15, 0.88, 0.05])
            atrophy_ax.axis("off")
            atrophy_ax.text(
                0.0,
                0.65,
                "Atrophy quantification of MRI:",
                fontsize=10,
                fontweight="bold",
            )
            atrophy_ax.text(
                0.0,
                0.20,
                "Not implemented in the current backend version.",
                fontsize=10,
                color=REPORT_RED,
            )

            _draw_section_bar(fig, 0.095, "Quality control")
            qc_ax = fig.add_axes([0.06, 0.03, 0.88, 0.05])
            qc_ax.axis("off")
            qc_ax.text(0.0, 0.75, f"Quality control: {qc}", fontsize=11, fontweight="bold")
            qc_ax.text(
                0.0,
                0.30,
                "A = good execution with generated biomarkers; B = execution completed but biomarkers require review; "
                "C = failed execution.",
                fontsize=7,
                color=REPORT_DARK_GREY,
            )

            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)

            return pdf_path

    except Exception as exc:
        print(f"[Warning] PDF report could not be created: {type(exc).__name__}: {exc}")
        return None


# -----------------------------------------------------------------------------
# Main Gradio callback
# -----------------------------------------------------------------------------

def run_darq_report(
    dat_file: str | None,
    mri_file: str | None,
    seg_file: str | None,
    subject_id: str,
    progress: gr.Progress = gr.Progress(track_tqdm=True),
):
    """Run the DARQ pipeline and return complete tables, images and PDF."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_subject = (subject_id or "subject").strip().replace(" ", "_") or "subject"
    run_dir = RUNS_DIR / f"run_{timestamp}_{safe_subject}"
    input_dir = run_dir / "inputs"
    output_dir = run_dir / "output"
    input_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    progress(0.05, desc="Preparing files")
    pipeline_script = _find_pipeline_script()
    dat_path = _copy_uploaded_file(dat_file, input_dir, "datscan")
    mri_path = _copy_uploaded_file(mri_file, input_dir, "T1w")
    seg_path = _copy_uploaded_file(seg_file, input_dir, "synthseg")

    command = [
        sys.executable,
        str(pipeline_script),
        "--dat",
        str(dat_path),
        "--mri",
        str(mri_path),
        "--seg",
        str(seg_path),
        "--o",
        str(output_dir),
        "--opt_str",
        DEFAULT_OPTIMIZER,
    ]

    if FORCE_RECOMPUTE:
        command.append("--force")
    if USE_CPU:
        command.append("--cpu")

    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT_DIR)

    progress(0.20, desc="Running DARQ pipeline")
    completed = subprocess.run(
        command,
        cwd=str(ROOT_DIR),
        env=env,
        text=True,
        capture_output=True,
        timeout=None,
    )

    progress(0.70, desc="Reading backend tables")
    sbr_raw = _read_first_tsv(output_dir, "*_sbr.tsv")
    symm_raw = _read_first_tsv(output_dir, "*_symm.tsv")

    if completed.returncode != 0:
        status = _status_text(completed, output_dir, sbr_raw, symm_raw)
        raise gr.Error(status)

    progress(0.82, desc="Creating image overlays")
    overlay_gallery = _create_overlay_gallery(mri_path, output_dir, run_dir)

    progress(0.92, desc="Creating PDF report")
    status = _status_text(completed, output_dir, sbr_raw, symm_raw)
    pdf_path = _create_pdf_report(
        run_dir=run_dir,
        subject_id=safe_subject,
        dat_input_path=dat_path,
        mri_input_path=mri_path,
        raw_sbr=sbr_raw,
        raw_symm=symm_raw,
        overlay_gallery=overlay_gallery,
        completed=completed,
        status_text=status,
    )

    progress(1.0, desc="Finished")

    return (
        _format_df_for_display(sbr_raw),
        _format_df_for_display(symm_raw),
        overlay_gallery,
        str(pdf_path) if pdf_path else None,
    )


# -----------------------------------------------------------------------------
# Gradio interface
# -----------------------------------------------------------------------------

CUSTOM_CSS = """
#main-title {text-align: center; margin-bottom: 0.2rem;}
#subtitle {text-align: center; color: #666; margin-bottom: 1.2rem;}
.gradio-container {max-width: 1500px !important;}
"""

with gr.Blocks(title=APP_TITLE, css=CUSTOM_CSS) as demo:
    gr.Markdown(f"# {APP_TITLE}", elem_id="main-title")
    gr.Markdown(
        "Upload one subject, run the DARQ pipeline, inspect the complete backend tables, "
        "review qualitative overlays and download the PDF report.",
        elem_id="subtitle",
    )

    with gr.Tab("1. Inputs"):
        with gr.Row():
            dat_input = gr.File(label="DaTSCAN (.nii or .nii.gz)", type="filepath")
            mri_input = gr.File(label="MRI / T1w (.nii or .nii.gz)", type="filepath")
            seg_input = gr.File(label="SynthSeg (.nii or .nii.gz)", type="filepath")

        subject_input = gr.Textbox(
            value="tutorial_subject",
            label="Subject / Case ID",
            placeholder="Example: sub-001",
        )

        run_button = gr.Button("Run DARQ report", variant="primary")

    with gr.Tab("2. Complete result tables"):
        sbr_output = gr.Dataframe(
            label="Complete SBR table generated by the pipeline",
            interactive=False,
            wrap=True,
        )
        symm_output = gr.Dataframe(
            label="Complete symmetry table generated by the pipeline",
            interactive=False,
            wrap=True,
        )

    with gr.Tab("3. Images"):
        overlay_output = gr.Gallery(
            label="MRI / registered DaTSCAN / overlay views",
            columns=1,
            height="auto",
            object_fit="contain",
        )

    with gr.Tab("4. PDF report"):
        pdf_output = gr.File(label="Download DARQ PDF report")

    run_button.click(
        fn=run_darq_report,
        inputs=[
            dat_input,
            mri_input,
            seg_input,
            subject_input,
        ],
        outputs=[
            sbr_output,
            symm_output,
            overlay_output,
            pdf_output,
        ],
        show_progress="minimal",
    )


if __name__ == "__main__":
    demo.launch()
