from __future__ import annotations

import os
import sys
from pathlib import Path

from webapp.worker.base_worker import BaseWorker


class DarqWorker(BaseWorker):
    """Worker responsible for executing DARQ jobs."""

    @property
    def pipeline_name(self) -> str:
        """Return the pipeline identifier."""

        return "darq"

    def build_pipeline_command(
        self,
        job_dir: Path,
    ) -> list[str]:
        """Build the command that executes DARQ."""

        input_dir = job_dir / "input"
        output_dir = job_dir / "output"

        dat_path = input_dir / "dat.nii.gz"
        mri_path = input_dir / "mri.nii.gz"
        seg_path = input_dir / "seg.nii.gz"

        if not dat_path.exists():
            raise FileNotFoundError(
                f"Missing DAT file: {dat_path}"
            )

        if not mri_path.exists():
            raise FileNotFoundError(
                f"Missing MRI file: {mri_path}"
            )

        if not seg_path.exists():
            raise FileNotFoundError(
                f"Missing SynthSeg file: {seg_path}"
            )

        use_darq_command = (
            os.getenv("USE_DARQ_COMMAND", "false").lower()
            == "true"
        )

        if use_darq_command:
            return [
                "darq",
                "--dat",
                str(dat_path),
                "--mri",
                str(mri_path),
                "--seg",
                str(seg_path),
                "--o",
                str(output_dir),
                "--cpu",
                "--force",
            ]

        pipeline_script = (
            self.root_dir / "scripts" / "dat2mri.py"
        )

        if not pipeline_script.exists():
            raise FileNotFoundError(
                f"Missing DARQ pipeline script: {pipeline_script}"
            )

        return [
            sys.executable,
            str(pipeline_script),
            "--dat",
            str(dat_path),
            "--mri",
            str(mri_path),
            "--seg",
            str(seg_path),
            "--o",
            str(output_dir),
            "--cpu",
            "--force",
        ]

    def collect_output_files(
        self,
        job_dir: Path,
    ) -> dict:
        """Collect files generated by DARQ."""

        output_dir = job_dir / "output"
        outputs = {}

        if not output_dir.exists():
            return outputs

        generic_file_index = 1

        for path in sorted(output_dir.rglob("*")):
            if not path.is_file():
                continue

            relative_path = path.relative_to(job_dir).as_posix()

            if path.name.endswith("_sbr.tsv"):
                outputs["sbr_tsv"] = relative_path

            elif path.name.endswith("_symm.tsv"):
                outputs["symmetry_tsv"] = relative_path

            elif path.suffix.lower() == ".pdf":
                outputs["pdf_report"] = relative_path

            else:
                key = f"file_{generic_file_index}"
                outputs[key] = relative_path
                generic_file_index += 1

        return outputs


def main() -> None:
    """Start the DARQ worker."""

    worker = DarqWorker()
    worker.run()


if __name__ == "__main__":
    main()